workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Tambahkan environment group jika ada
      vars:
        BASE_URL: "https://demo-kjavmj.prosesin.id/api"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze
      
      - name: Build iOS Simulator
        script: |
          flutter build ios --simulator --release --dart-define=BASE_URL=$BASE_URL
    
    artifacts:
      - build/ios/iphonesimulator/**/*.app
    
    publishing:
      email:
        recipients:
          - claudio.nehemia83@gmail.com
        notify:
          success: true
          failure: true