name: absensi_kjavjm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # HTTP Requests
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # File Operations
  file_picker: ^8.0.0+1
  
  # Environment Configuration
  flutter_dotenv: ^6.0.0
  
  # UI Components
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Internationalization
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

# ✅ Konfigurasi Icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

# ✅ Konfigurasi Splash Screen
flutter_native_splash:
  color: "#ffffff" # warna background splash
  image: assets/icons/app_icon.png # logo yang ditampilkan
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/icons/app_icon.png
